function elf_maingui_visibility(gui, status)

col = {'r', [1 .6 0], [0 .5 0], 'g'};    % colors indicating analysis progress
tooltips = {{'No images were found in this folder.', ...
    'Only raw image files were found in this folder. Please convert them into uncompressed DNG files with Adobe''s DNG-Converter (see ELF manual for instructions).', ...
    '', ...
    'Usable images were found in this folder (either DNGs or non-raw). Proceed to the next step.'}, ...
    {'The images in this data set have not been filtered yet. Press this button to start filtering.', ...
    'Some, but not all of the images in this data set have been filtered. Press this button to start filtering. You can use the text field below to enter a range of images to process.', ...
    'All images in this data set have been filtered, but some of the images have been modified since then. Press this button to re-filter all images or proceed to the next step.', ...
    'All images in this data set have been filtered. Proceed to the next step.'}, ...
    {'The descriptors for this data set have not been calculated yet. Press this button to start calculating.', ...
    'Some, but not all of the descriptors in this data set have been calculated. Press this button to start calculating. You can use the text field below to enter a range of images to process.', ...
    'All descriptors in this data set have been calculated, but some of the images have been modified or re-filtered since then. Press this button to re-calculate all descriptors or proceed to the next step.', ...
    'All descriptors in this data set have been calculated. Proceed to the next step.'}, ...
    {'The summary for this data set has not been calculated yet.', ...
    '', ...
    'A summary has been calculated, but some images have been modified, re-filtered or recalculated afterwards. Press this cutton to recalculate the summary.', ...
    'The summary has been calculated and saved for this data set.'}};

% set button colours
for i = 1:size(status, 1)
    set(gui.p(i).b1, 'backgroundcolor', col{status(i, 1)+1}, 'tooltip', tooltips{1}{status(i, 1)+1});
    set(gui.p(i).b2, 'backgroundcolor', col{status(i, 2)+1}, 'tooltip', tooltips{2}{status(i, 2)+1});
    set(gui.p(i).b3, 'backgroundcolor', col{status(i, 3)+1}, 'tooltip', tooltips{3}{status(i, 3)+1});
    set(gui.p(i).b4, 'backgroundcolor', col{status(i, 4)+1}, 'tooltip', tooltips{4}{status(i, 4)+1});
    
    if status(i, 4), en = 'on'; else en = 'off'; end % only enable show button if summary has been calculated
    set(gui.p(i).b6, 'enable', en);
end