% skypipewarrior
stem = "/Users/jamesf/Documents/Starry Project/Light Pollution Imaging/Figure1/";
folders = {...fullfile(stem, "LPexper-20171121-LPexper-OvercastWits"),...
    ...fullfile(stem, "LPexper-20181122_Fullmoon_BelaBela"),...
    fullfile(stem, "LPexper-20181122-WaxGibbous-Wits"),...
    fullfile(stem, "LPexper-20181127-LowMWay-Thornwood"),...
    fullfile(stem, "LPexper-20181128-LowMWayandMushrooms-Wits")};
for(i = 1:length(folders))
    skypipe(char(folders{i}))
end
fprintf("\n\n\t\tCongratulations, you did it!\t\t\n\n")